sudo: required
language: minimal
dist: xenial
services:
  - docker

env:
  global:
    - DOCKER_IMAGE_SLUG: "${TRAVIS_REPO_SLUG,,}"
  matrix:
    - distribution: Ubuntu
      distribution_version: bionic
      distribution_alias: 18.04
      init: /lib/systemd/systemd
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distribution: Ubuntu
      distribution_version: xenial
      distribution_alias: 16.04
      init: /lib/systemd/systemd
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distribution: EL
      distribution_version: "7"
      init: /usr/lib/systemd/systemd
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distribution: EL
      distribution_version: "6"
      init: /sbin/init
      run_opts: ""
    - distribution: Debian
      distribution_version: stretch
      distribution_alias: 9
      init: /lib/systemd/systemd
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distribution: Debian
      distribution_version: jessie
      distribution_alias: 8
      init: /lib/systemd/systemd
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distribution: Fedora
      distribution_version: "24"
      init: /usr/lib/systemd/systemd
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distribution: ArchLinux
      distribution_version: latest
      init: /usr/lib/systemd/systemd
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distribution: OracleLinux
      distribution_version: "7.3"
      init: /usr/lib/systemd/systemd
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"
    - distribution: OracleLinux
      distribution_version: "6.8"
      init: /sbin/init
      run_opts: ""
    - distribution: opensuse
      distribution_version: "42.2"
      init: /usr/lib/systemd/systemd
      run_opts: "--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro"

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

script:
  - docker build -t "${DOCKER_IMAGE_SLUG}":"${distribution,,}"-"${distribution_version}" core/"${distribution}"/"${distribution_version}"
  - container_id=$(mktemp)
  # Start The Built Container In The Background
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/role_under_test:ro ${run_opts} "${DOCKER_IMAGE_SLUG}":"${distribution,,}"-"${distribution_version}" "${init}" > "${container_id}"'

  # Ansible syntax check.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml --syntax-check'

  # Test role.
  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/test.yml'

deploy:
  provider: script
  skip_cleanup: true
  script: bash pushtoregistry.sh
  on:
    branch: master
